---
version: '2'
services:
  consul:
    image: consul:latest
    ports:
      - 8500:8500
      - 8600:8600/udp
    command: agent -dev -ui -client=0.0.0.0

  mft-controller:
    image: squadronteam/mft-controller:latest
    build: ../controller
    ports:
      - 9093:9093
    depends_on:
      - consul

  mft-resource-service:
    image: squadronteam/mft-resource-service:latest
    build: ../services/resource-service/server
    ports:
      - 7002:7002

  mft-secret-service:
    image: squadronteam/mft-secret-service:latest
    build: ../services/secret-service/server
    ports:
      - 7003:7003

  mft-agent:
    image: squadronteam/mft-agent:latest
    build: ../agent
    ports:
     - 9094:9094
    depends_on:
      - consul
      - mft-secret-service
      - mft-resource-service

  mft-api:
    image: squadronteam/mft-api:latest
    build: ../api/service
    ports:
      - 7004:7004
    depends_on:
      - consul
      - mft-resource-service
      - mft-secret-service